version: '3.7'

services:
  app:
    image: alvargran/picture-sharing-online:v6
    container_name: nextjs_app
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: 1337
      MYSQL_DATABASE: your_database
      MYSQL_USER: root
    volumes:
      - /uploads:/app/uploads
      - ./config:/app/config
    networks:
      - app-network
    expose:
      - 3000

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1337
      MYSQL_DATABASE: your_database
      MYSQL_PASSWORD: 1337
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./webroot:/var/www/certbot  # Mount the webroot directory
    depends_on:
      - app
      - certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/var/lib/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
      - ./webroot:/var/www/certbot  # Mount the webroot directory
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot -n --quiet; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

volumes:
  certs:
  certbot-data:
  certbot-logs:
  webroot:  # Volume for the webroot directory

networks:
  app-network:
