version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1337
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: 1337
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  app:
    image: alvargran/picture-sharing-online:latest 
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: 1337
      MYSQL_DATABASE: your_database
    volumes:
      - uploads-data:/app/public/uploads
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  migrate:
    image: alvargran/picture-sharing-online:latest
    command: sh -c "npx sequelize-cli db:migrate"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: 1337
      MYSQL_DATABASE: your_database
    volumes:
      - ./config:/app/config  # Ensures config is available inside the container
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  mysql-data:
  uploads-data:

networks:
  app-network:
    driver: overlay

