version: '3.7'

services:
  app:
    image: alvargran/picture-sharing-online:v6
    container_name: nextjs_app
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: 1337
      MYSQL_DATABASE: your_database
      MYSQL_USER: root
    volumes:
      - /uploads:/app/uploads
      - ./config:/app/config
    networks:
      - app-network
    expose:
      - 3000  # Expose port 3000 to other services in the network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1337
      MYSQL_DATABASE: your_database
      MYSQL_PASSWORD: 1337
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'  # Expose port 80 for HTTP traffic
      - '443:443'  # Optionally expose port 443 for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
      - ./certs:/etc/nginx/certs  # SSL certificates (optional)
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
